version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cakeday-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: cakeday_db
      MYSQL_USER: cakedaY
      MYSQL_PASSWORD: cakeday1234
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d